server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jiazhong_2026_1
    username: root
    password: 20050217
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource